-- MySQL Script generated by MySQL Workbench
-- Wed Jan 13 13:54:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema elibrary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elibrary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elibrary` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_czech_ci ;
USE `elibrary` ;

-- -----------------------------------------------------
-- Table `elibrary`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(80) NULL,
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` DATETIME NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elibrary`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `author` VARCHAR(100) NOT NULL,
  `content` TEXT NULL,
  `cover_url` VARCHAR(255) NULL,
  `active` TINYINT(1) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elibrary`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elibrary`.`user_rated_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`user_rated_book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stars` INT(1) NULL,
  `review` TEXT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id` INT NOT NULL,
  `books_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_rated_book_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_user_rated_book_books1_idx` (`books_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_rated_book_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `elibrary`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_rated_book_books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `elibrary`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elibrary`.`books_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elibrary`.`books_has_categories` (
  `books_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`books_id`, `categories_id`),
  INDEX `fk_books_has_categories_categories1_idx` (`categories_id` ASC) VISIBLE,
  INDEX `fk_books_has_categories_books_idx` (`books_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_has_categories_books`
    FOREIGN KEY (`books_id`)
    REFERENCES `elibrary`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_has_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `elibrary`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
